
package javafunctions;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio Lozano
 */
public class Board extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jButton1.setText("Cartesiano");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("F(x) = 1/x");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("F(x) = e ^x");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("F(x) = x^1/3");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("F(x) = log n de X");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("F(x) = sen de x");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("F(x)= cos de X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("F(x)= tan de x");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Circle = Radio");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Custom circle");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton3)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5))
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9)
                        .addGap(28, 28, 28)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Graphics cart = jPanel1.getGraphics();
        cart.setColor(Color.DARK_GRAY);
        
        cart.drawLine(0, 250, 500, 250);
        cart.drawLine(250, 0, 250, 500); 
        
        //horizotal lines
        cart.setColor(Color.gray);
        cart.drawLine(150, 0, 150, 500); 
        cart.drawLine(50, 0, 50, 500); 
        cart.drawLine(350, 0, 350, 500); 
        cart.drawLine(450, 0, 450, 500); 
        
        //vertical Lines
        cart.setColor(Color.LIGHT_GRAY);
        cart.drawLine(0, 150, 500, 150); 
        cart.drawLine(0, 50, 500, 50); 
        cart.drawLine(0, 350, 500, 350); 
        cart.drawLine(0, 450, 500, 450); 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        function1();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        function2();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        function3();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        repaint();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        function4();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        function5Sen();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        function6Cos();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        function7Tan();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        circle1();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        circle2();
    }//GEN-LAST:event_jButton11ActionPerformed

    public void function1(){
        Graphics func = jPanel1.getGraphics();
        func.setColor(Color.blue);
        
        for (double x = -250; x <= 250; x+=1) { 
        if (x == 0) continue; 

        double y = (1.0 / x) * 100*2; 
        func.drawOval(250 +(int)(x * 6) - 3, 250 - (int)(y*6) - 3, 6, 6);

        }
    }
    
    public void function2(){
         Graphics func = jPanel1.getGraphics();
        func.setColor(Color.red);
        
        for (double x = -250; x <= 250; x+= 0.567) {
            double y = Math.pow(Math.E,x)*100;
            
            func.drawOval(247+(int)(x*62), 247-(int)y, 6, 6);    
        }
        
    }
    
    public void function3(){
        Graphics func = jPanel1.getGraphics();
        func.setColor(Color.orange);
        
        String num = JOptionPane.showInputDialog(this, "enter your number: ");
        
         double nm = Double.parseDouble(num);
        //int nm = Integer.parseInt(num);
        
         for (double x = -250; x <= 250; x+=0.56) {
        double y;

        // Evitar cálculos inválidos cuando nm es par y x es negativo
        if (nm % 2 == 0 && x < 0) {
            continue; // Saltar iteraciones con valores inválidos
        } else {
            y = Math.pow(Math.abs(x), 1.0 / nm) * 100; // Aplicar escala
            if (x < 0 && nm % 2 != 0) {
                y = -y; // Manejar raíces impares con negativos
            }
        }
            
            func.drawOval(247+(int)(x*2), 247-(int)y, 6, 6);
        }
    }
    
    public void function4(){
        Graphics func = jPanel1.getGraphics();
        func.setColor(Color.orange);
        
        String num = JOptionPane.showInputDialog(this,"Please enter your number; ");
        
        double nm = Double.parseDouble(num);
        
        if (nm <= 0 || nm == 1) {
        JOptionPane.showMessageDialog(this, "Base must be greater than 0 and not equal to 1.");
        return;
    }

    for (double x = 1; x <= 250; x+=0.5) { // Empezamos en x = 1 porque log(x) no existe para x <= 0
        double y = (Math.log(x) / Math.log(nm)) * 100; // Aplicar escala

        func.drawOval(250 + (int)(x * 2), 250 - (int)y, 6, 6); // Se ajusta la escala en x
    }
    }
    
    public void function5Sen(){
        Graphics func = jPanel1.getGraphics();
        func.setColor(Color.gray);
        
        for (double x = -250; x < 250; x+=1) {
            double cvs = Math.toRadians(x);
            double y = Math.sin(cvs)*65;
            
            func.drawOval(247+(int)x, 247-(int)y, 6, 6);
        }
        
    }
    
    public void function6Cos(){
        Graphics func = jPanel1.getGraphics();
        func.setColor(Color.pink);
        
        for (int x = -250; x < 250; x+=1) {
            double upd = Math.toRadians(x);
            double y = Math.cos(upd)*65;
            
            func.drawOval(247+x, 247-(int)y, 6, 6);
        }
        
    }
    
    public void function7Tan(){
        Graphics func = jPanel1.getGraphics();
        func.setColor(Color.magenta);
        
        for (int x = -250; x < 250; x+=1) {
            double upd = Math.toRadians(x);
            double y = Math.tan(upd)*65;
            
            func.drawOval(247+x, 247-(int)y, 6, 6);
            
        }
        
    }
    
    public void circle1(){
        Graphics func = jPanel1.getGraphics();
        
        String [] opts = {"Red","Yellow","blue"};
        int sCo = JOptionPane.showOptionDialog(this, "choose your favorite colore","", 
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,opts,opts[0]);
        
        switch (sCo){
            case 0:
                func.setColor(Color.red);
                break;
            case 1:
                func.setColor(Color.yellow);
                break;
            case 2:
                func.setColor(Color.blue);
                break;
        }
        
        String rad = JOptionPane.showInputDialog(this, "enter your radio's circle: ");
        double radN = Double.parseDouble(rad);
        if (radN <= 0) {
            JOptionPane.showMessageDialog(this, "we cannot perform 'cause the radio is less than 0");
            return;
        }
        try{
            
        String coo = JOptionPane.showInputDialog(this, "enter your coordenates, X and Y: ");
        
        String [] pts = coo.split(",");
        
        int px = Integer.parseInt(pts[0]);
        int py = Integer.parseInt(pts[1]);
        
        int mid = (int)(radN/2.0);
        
        func.drawOval(250-mid+px, 250-mid-py, (int)radN, (int)radN);
        
        //Area
        double area = Math.PI * Math.pow(radN, 2);
        //perimeter
        double perim = 2 * Math.PI * radN;
        JOptionPane.showMessageDialog(this,"the Are is: "+area +"\n The perimeter is: "+perim);  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "You messed up, try again!!");
        }
    }
    
    public void circle2(){
       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
