
package com.mycompany.fisica;

import javax.swing.JOptionPane;

/**
 *
 * @author osmar
 */
public class NewtonSecondLaw extends javax.swing.JFrame {

    /**
     * Creates new form NewtonSecondLaw
     */
    public NewtonSecondLaw() {
        initComponents();
        setCombo();
        this.setLocationRelativeTo(null);
        
        jButton2.addActionListener(evt -> performCalculation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Que plano utilizaras?");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Que deseas encontrar?");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Fuerza:");

        jLabel4.setText("Masa (M):");

        jLabel5.setText("Aceleraciòn:");

        jLabel6.setText("Fricciòn");

        jLabel7.setText("Coeficiente de fricciòn:");

        jLabel8.setText("Angulo:");

        jLabel9.setText("Peso (w):");

        jLabel10.setText("Peso en X:");

        jLabel11.setText("Wx");

        jLabel12.setText("Peso en Y:");

        jLabel13.setText("Wy");

        jLabel14.setText("Resultado Final:");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Calcular");

        jButton3.setText("Nuevo Calculo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel15.setText("Si desconoce algun dato por favor ingrese el numero 0");

        jLabel16.setText("Tensiòn:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel16)
                                    .addGap(195, 195, 195))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addComponent(jLabel14)
                                            .addGap(26, 26, 26)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(42, 42, 42)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addGap(32, 32, 32)
                                                        .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextField3))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel4)
                                                            .addComponent(jLabel3))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                                            .addComponent(jTextField2)))))))
                                    .addGap(42, 42, 42)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel12))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                            .addComponent(jTextField6)
                                            .addComponent(jTextField7))
                                        .addComponent(jLabel13)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addGap(46, 46, 46)
                                    .addComponent(jButton3))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(137, 137, 137)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(8, 8, 8)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel15)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jLabel14)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clean();
    }//GEN-LAST:event_jButton3ActionPerformed

     private void setCombo(){
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Plano horizontal");
        jComboBox1.addItem("Plano Inclinado");
        jComboBox1.addItem("Plano vertical");
        
        jComboBox2.removeAllItems();
        jComboBox2.addItem("Fuerza");
        jComboBox2.addItem("Masa");
        jComboBox2.addItem("Aceleración");
        jComboBox2.addItem("Fricción");
        jComboBox2.addItem("Coeficiente de fricción");
        jComboBox2.addItem("Angulo");
        jComboBox2.addItem("Peso");
        jComboBox2.addItem("Tensiòn");
          
    }
     
     private void performCalculation() {
    String plano = (String) jComboBox1.getSelectedItem();
    String solver = (String) jComboBox2.getSelectedItem();

    double g = 9.8;

    try {
        double fuerza = Double.parseDouble(jTextField1.getText());
        double masa = Double.parseDouble(jTextField2.getText());
        double aceleracion = Double.parseDouble(jTextField3.getText());
        double friccionManual = Double.parseDouble(jTextField4.getText());
        double mu = Double.parseDouble(jTextField5.getText());
        double angulo = Double.parseDouble(jTextField6.getText());
        double tensionInput = Double.parseDouble(jTextField9.getText());

        double anguloRad = Math.toRadians(angulo);
        double peso = masa > 0 ? masa * g : 0;
        double pesoX = (angulo > 0) ? peso * Math.sin(anguloRad) : 0;
        double pesoY = (angulo > 0) ? peso * Math.cos(anguloRad) : peso;
        double friccion = (mu > 0 && pesoY > 0) ? mu * pesoY : 0;

        // Mostrar datos reutilizables
        jTextField7.setText(String.format("%.2f", peso));
        jLabel11.setText(String.format("%.2f", pesoX));
        jLabel13.setText(String.format("%.2f", pesoY));
        jTextField4.setText(String.format("%.2f", friccion));

        switch (solver) {
            case "Aceleración":
                if (plano.equals("Plano Inclinado")) {
                    aceleracion = g * (Math.sin(anguloRad) - mu * Math.cos(anguloRad));
                    jTextField3.setText(String.format("%.3f", aceleracion));
                    jTextField8.setText(String.format("%.3f m/s²", aceleracion));
                    return;
                } else if (plano.equals("Plano vertical")) {
                    if (masa > 0 && tensionInput > 0) {
                        aceleracion = (tensionInput - masa * g) / masa;
                        jTextField3.setText(String.format("%.3f", aceleracion));
                        jTextField8.setText(String.format("%.3f m/s²", aceleracion));
                        return;
                    }
                }

                if (masa > 0 && fuerza > 0) {
                    aceleracion = (fuerza - friccion) / masa;
                    jTextField3.setText(String.format("%.3f", aceleracion));
                    jTextField8.setText(String.format("%.3f m/s²", aceleracion));
                } else {
                    jTextField8.setText("Faltan datos para aceleración");
                }
                break;

            case "Fuerza":
                if (masa > 0 && aceleracion > 0) {
                    fuerza = masa * aceleracion + friccion;
                    jTextField1.setText(String.format("%.2f", fuerza));
                    jTextField8.setText(String.format("%.2f N", fuerza));
                } else {
                    jTextField8.setText("Faltan datos para fuerza");
                }
                break;

            case "Masa":
                if (aceleracion > 0 && fuerza > 0) {
                    masa = (fuerza - friccion) / aceleracion;
                    peso = masa * g;
                    pesoX = peso * Math.sin(anguloRad);
                    pesoY = peso * Math.cos(anguloRad);

                    jTextField2.setText(String.format("%.2f", masa));
                    jTextField7.setText(String.format("%.2f", peso));
                    jLabel11.setText(String.format("%.2f", pesoX));
                    jLabel13.setText(String.format("%.2f", pesoY));
                    jTextField8.setText(String.format("%.2f kg", masa));
                } else {
                    jTextField8.setText("Faltan datos para masa");
                }
                break;

            case "Fricción":
                if (mu > 0 && masa > 0) {
                    friccion = mu * masa * g;
                    if (plano.equals("Plano Inclinado")) {
                        friccion = mu * masa * g * Math.cos(anguloRad);
                    }
                    jTextField4.setText(String.format("%.2f", friccion));
                    jTextField8.setText(String.format("%.2f N", friccion));
                } else {
                    jTextField8.setText("Faltan datos para fricción");
                }
                break;

            case "Coeficiente de fricción":
                if (friccionManual > 0 && masa > 0) {
                    if (plano.equals("Plano Inclinado")) {
                        mu = friccionManual / (masa * g * Math.cos(anguloRad));
                    } else {
                        mu = friccionManual / (masa * g);
                    }
                    jTextField5.setText(String.format("%.3f", mu));
                    jTextField8.setText(String.format("%.3f", mu));
                } else {
                    jTextField8.setText("Faltan datos para coeficiente de fricción");
                }
                break;

            case "Peso":
                if (masa > 0) {
                    peso = masa * g;
                    jTextField7.setText(String.format("%.2f", peso));
                    jTextField8.setText(String.format("%.2f N", peso));
                } else {
                    jTextField8.setText("Falta masa para calcular peso");
                }
                break;

            case "Angulo":
                jTextField8.setText("El ángulo debe ser proporcionado directamente");
                break;

            case "Tensiòn":
                double tension = 0;

                if (masa > 0 && aceleracion != 0) {
                    if (plano.equals("Plano Inclinado")) {
                        tension = masa * aceleracion + masa * g * Math.sin(anguloRad) + mu * masa * g * Math.cos(anguloRad);
                    } else if (plano.equals("Plano vertical")) {
                        tension = masa * (g + aceleracion);
                    } else { // horizontal
                        tension = masa * aceleracion + friccion;
                    }
                    jTextField9.setText(String.format("%.2f", tension));
                    jTextField8.setText(String.format("%.2f N", tension));
                } else {
                    jTextField8.setText("Faltan datos para calcular tensión");
                }
                break;

            default:
                jTextField8.setText("Opción no válida");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa datos válidos (usa 0 si desconoces alguno)", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

     
     private void clean(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jLabel11.setText("");
        jLabel13.setText("");
    }
    
    
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
